### ISSUE TITLE
Higher Quality Embed

### ISSUE THREAD

**Issue by Valafi** [dragonismcode/fxtiktok#10]
I've noticed that the embedded video is the one of the lowest qualities available. I'm guessing this is because it needed to be h264 encoded to work in Discord. However, Discord now supports h265 as mentioned in [last months blog post](https://discord.com/blog/discord-patch-notes-july-1-2024). It's not working perfectly for everyone yet, but it's there! Anyways, this is important because TikTok offers much better resolutions in h265.

Here's a list of available formats when using yt-dlp:
![yt-dlp_formats](https://github.com/user-attachments/assets/203a7322-823b-4d1b-8ebb-ed8e735bfc2a)

It'd be great if the full resolution video could be embedded instead of the halved h264 one. Either way, thanks for putting so much effort into this project.

**Comment by okdargy** [comment]
Currently, we are using tikwm.com for [fetching the actual video](https://github.com/okdargy/fxTikTok/blob/hono-rewrite/src/index.ts#L231C1-L231C75) since TikTok has some sort of token system. I talked about it more [here](https://github.com/okdargy/fxTikTok/issues/7#issuecomment-2131415125).

I'll definitely look more into finding a different way to fetch videos in a higher quality such as h265 and update this issue if I find anything new.

**Comment by okdargy** [comment]
Alright, turns out tikwm.com's /hdplay endpoint actually just gives h265... it's as simple as that.

![image](https://github.com/user-attachments/assets/0c6577f9-073d-4438-b610-e54296e24897)
