### ISSUE TITLE
[BUG] Alternative embedding modes doesn't work on some tiktoks

### ISSUE THREAD

**Issue by Kyrela** [dragonismcode/fxtiktok#15]
Alternative embedding modes (e.g. `a.` and `d.`) are preventing the embed to render in Discord, for some videos (not tested on photos).

Example of a functional tiktok:
https://tiktok.com/@kadirrrx24/video/7325911295549558048 (https://a.tnktok.com/@kadirrrx24/video/7325911295549558048)

Example of a non-functional tiktok:
https://a.tnktok.com/@kadirrrx24/video/7325911295549558048 (https://a.tnktok.com/@tf1info/video/7400005509186702625)

They work prefectly without the `a.`.

*Note: `a.` is used is theses examples, but they are also non-functionnal with `d.`.*

**Comment by okdargy** [comment]
Thank you for reporting this bug! It turns out, Discord has a 256 character limit on some embed values and when those values exceed their limit, they don't truncate by default but just.. **fail**.

If you have any more bugs or features you would like to see, feel free to open another issue. Have a nice day!

**Comment by Kyrela** [comment]
Thank you! I suppose that the fact that it also doesn't work with `d.` is related to #14?

**Comment by okdargy** [comment]
> Thank you! I suppose that the fact that it also doesn't work with `d.` is related to #14?

I'll look more into them not working with `d.`, I didn't test that.
