### ISSUE TITLE
Doesn't embed, domain for sale?

### ISSUE THREAD

**Issue by julianpoelmann** [dragonismcode/fxtiktok#3]
Doesn't embed and the link will say the domain is for sale

**Comment by okdargy** [comment]
Hey there, thanks for opening an issue!

I renewed the domain in #2 so I don't see why it would be up for sale.. I tested it with a video and it properly embeds for me. Are you sure you are using `s/i/n` and it's translating to tnktok.com? 

If so, please send the full URL you are sending so I can try and debug what the problem is. 

Thank you!

**Comment by julianpoelmann** [comment]
Wait so it doesn't work like fxtwitter? As in I have to change the I to make it work?

(I don't have the link rn and forgot what it was-)

Also if possible maybe it could be cool to add the d. Argument infront of the link to provide a direct video link (some programs don't properly embed but this method let's it work even in video players. Same like d.fxtwitter)

**Comment by okdargy** [comment]
> Wait so it doesn't work like fxtwitter? As in I have to change the I to make it work?

Well, just like fxTwitter, you will need to change the domain to ours, `tnktok.com` but it's just that we don't own `fxtiktok.com` (presumably owned by Douyin)

> Also if possible maybe it could be cool to add the d. Argument infront of the link to provide a direct video link (some programs don't properly embed but this method let's it work even in video players. Same like d.fxtwitter)

Very possible, I'll see about adding direct media later on, thanks for the suggestion!
