### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by AutumnRivers** [dragonismcode/fxtiktok#7]
Tiktok changed their API; https://github.com/imputnet/cobalt/issues/497

This is causing "Unexpected end of JSON input" errors with fxTikTok. This happened previously with https://github.com/okdargy/fxTikTok/issues/6 during the last API change.

**Comment by helish88** [comment]
![image](https://github.com/okdargy/fxTikTok/assets/52331802/69673d68-441b-409b-ad7a-f1d3c232bb82)

**Comment by okdargy** [comment]
Apologies for not getting back to you sooner, I am currently investigating and playing around with trying to find a way to extract a device_id from my jailbroken phone. I will update this issue with anything I find. Thank you all for your patience.

**Comment by okdargy** [comment]
Since I can't extract my device_id from my phone due to TikTok's SSL pinning techniques, I've decided to take a web-based scraping approach (just like Cobalt) as a backup in case TikTok changes their API again.

**Comment by okdargy** [comment]
Alright, pushed a fix and tnktok.com should be up and running! I did have to fall back on tikwm.com to redirect media because while experimenting with scraping TikTok's web rehydration data, I figured out they automatically add some sort of token to the `playAddr` URL so you can only use the media URL with the `ttwid` cookie they assign you and I don't want to pipe the entire media file thru Cloudflare Workers and use a bunch of bandwidth.

![image](https://github.com/okdargy/fxTikTok/assets/76412158/a3c6c950-aacf-4f02-9bc4-d79d76a7ef9c)

 Thank you all for the patience, feel free to open an issue for any bugs or future features you would like to see. 😊
